import sqlite3
import json
pointsValue = {
    "Bulbasaur": { "points": 0 },
    "Ivysaur": { "points": 0 },
    "Venusaur": { "points": 2 },
    "Charmander": { "points": 0 },
    "Charmeleon": { "points": 0 },
    "Charizard": { "points": 1 },
    "Squirtle": { "points": 0 },
    "Wartortle": { "points": 0 },
    "Blastoise": { "points": 1 },
    "Caterpie": { "points": 0 },
    "Metapod": { "points": 0 },
    "Butterfree": { "points": 0 },
    "Weedle": { "points": 0 },
    "Kakuna": { "points": 0 },
    "Beedrill": { "points": 0 },
    "Pidgey": { "points": 0 },
    "Pidgeotto": { "points": 0 },
    "Pidgeot": { "points": 0 },
    "Rattata": { "points": 0 },
    "Raticate": { "points": 0 },
    "Spearow": { "points": 0 },
    "Fearow": { "points": 0 },
    "Ekans": { "points": 0 },
    "Arbok": { "points": 0 },
    "Pikachu": { "points": 0 },
    "Raichu": { "points": 0 },
    "Sandshrew": { "points": 0 },
    "Sandslash": { "points": 0 },
    "Nidoran♀": { "points": 0 },
    "Nidorina": { "points": 0 },
    "Nidoqueen": { "points": 1 },
    "Nidoran♂": { "points": 0 },
    "Nidorino": { "points": 0 },
    "Nidoking": { "points": 1 },
    "Clefairy": { "points": 0 },
    "Clefable": { "points": 2 },
    "Vulpix": { "points": 0 },
    "Ninetales": { "points": 0, "pointsHa": 1 },
    "Jigglypuff": { "points": 0 },
    "Wigglytuff": { "points": 0 },
    "Zubat": { "points": 0 },
    "Golbat": { "points": 0 },
    "Oddish": { "points": 0 },
    "Gloom": { "points": 0 },
    "Vileplume": { "points": 0 },
    "Paras": { "points": 0 },
    "Parasect": { "points": 0 },
    "Venonat": { "points": 0 },
    "Venomoth": { "points": 0 },
    "Diglett": { "points": 0 },
    "Dugtrio": { "points": 1 },
    "Meowth": { "points": 0 },
    "Persian": { "points": 0 },
    "Psyduck": { "points": 0 },
    "Golduck": { "points": 0 },
    "Mankey": { "points": 0 },
    "Primeape": { "points": 0 },
    "Growlithe": { "points": 0 },
    "Arcanine": { "points": 0 },
    "Poliwag": { "points": 0 },
    "Poliwhirl": { "points": 0 },
    "Poliwrath": { "points": 0 },
    "Abra": { "points": 0 },
    "Kadabra": { "points": 0 },
    "Alakazam": { "points": 1 },
    "Machop": { "points": 0 },
    "Machoke": { "points": 0 },
    "Machamp": { "points": 0 },
    "Bellsprout": { "points": 0 },
    "Weepinbell": { "points": 0 },
    "Victreebel": { "points": 0 },
    "Tentacool": { "points": 0 },
    "Tentacruel": { "points": 1 },
    "Geodude": { "points": 0 },
    "Graveler": { "points": 0 },
    "Golem": { "points": 0 },
    "Ponyta": { "points": 0 },
    "Rapidash": { "points": 0 },
    "Slowpoke": { "points": 0 },
    "Slowbro": { "points": 1 },
    "Magnemite": { "points": 0 },
    "Magneton": { "points": 0 },
    "Farfetch'd": { "points": 0 },
    "Doduo": { "points": 0 },
    "Dodrio": { "points": 0 },
    "Seel": { "points": 0 },
    "Dewgong": { "points": 0 },
    "Grimer": { "points": 0 },
    "Muk": { "points": 0 },
    "Shellder": { "points": 0 },
    "Cloyster": { "points": 1 },
    "Gastly": { "points": 0 },
    "Haunter": { "points": 0 },
    "Gengar": { "points": 1 },
    "Onix": { "points": 0 },
    "Drowzee": { "points": 0 },
    "Hypno": { "points": 0 },
    "Krabby": { "points": 0 },
    "Kingler": { "points": 0 },
    "Voltorb": { "points": 0 },
    "Electrode": { "points": 1 },
    "Exeggcute": { "points": 0 },
    "Exeggutor": { "points": 1 },
    "Cubone": { "points": 0 },
    "Marowak": { "points": 1 },
    "Hitmonlee": { "points": 1 },
    "Hitmonchan": { "points": 0 },
    "Lickitung": { "points": 0 },
    "Koffing": { "points": 0 },
    "Weezing": { "points": 0 },
    "Rhyhorn": { "points": 0 },
    "Rhydon": { "points": 0 },
    "Chansey": { "points": 3 },
    "Tangela": { "points": 1 },
    "Kangaskhan": { "points": 0 },
    "Horsea": { "points": 0 },
    "Seadra": { "points": 0 },
    "Goldeen": { "points": 0 },
    "Seaking": { "points": 0 },
    "Staryu": { "points": 0 },
    "Starmie": { "points": 0 },
    "Mr.Mime": { "points": 0 },
    "Scyther": { "points": 0 },
    "Jynx": { "points": 0 },
    "Electabuzz": { "points": 0 },
    "Magmar": { "points": 0 },
    "Pinsir": { "points": 0 },
    "Tauros": { "points": 0 },
    "Magikarp": { "points": 0 },
    "Gyarados": { "points": 1 },
    "Lapras": { "points": 0 },
    "Ditto": { "points": 0, "pointsHa": 3 },
    "Eevee": { "points": 1 },
    "Vaporeon": { "points": 1 },
    "Jolteon": { "points": 0 },
    "Flareon": { "points": 1 },
    "Porygon": { "points": 0 },
    "Omanyte": { "points": 0 },
    "Omastar": { "points": 1 },
    "Kabuto": { "points": 0 },
    "Kabutops": { "points": 0 },
    "Aerodactyl": { "points": 1 },
    "Snorlax": { "points": 2 },
    "Articuno": { "points": 0 },
    "Zapdos": { "points": 1 },
    "Moltres": { "points": 1 },
    "Dratini": { "points": 0 },
    "Dragonair": { "points": 0 },
    "Dragonite": { "points": 1 },
    "Mewtwo": { "points": 3 },
    "Mew": { "points": 1 },
    "Chikorita": { "points": 0 },
    "Bayleef": { "points": 0 },
    "Meganium": { "points": 0 },
    "Cyndaquil": { "points": 0 },
    "Quilava": { "points": 0 },
    "Typhlosion": { "points": 0 },
    "Totodile": { "points": 0 },
    "Croconaw": { "points": 0 },
    "Feraligatr": { "points": 0 },
    "Sentret": { "points": 0 },
    "Furret": { "points": 0 },
    "Hoothoot": { "points": 0 },
    "Noctowl": { "points": 0 },
    "Ledyba": { "points": 0 },
    "Ledian": { "points": 0 },
    "Spinarak": { "points": 0 },
    "Ariados": { "points": 0 },
    "Crobat": { "points": 1 },
    "Chinchou": { "points": 0 },
    "Lanturn": { "points": 0 },
    "Pichu": { "points": 0 },
    "Cleffa": { "points": 0 },
    "Igglybuff": { "points": 0 },
    "Togepi": { "points": 0 },
    "Togetic": { "points": 0 },
    "Natu": { "points": 0 },
    "Xatu": { "points": 0 },
    "Mareep": { "points": 0 },
    "Flaaffy": { "points": 0 },
    "Ampharos": { "points": 0 },
    "Bellossom": { "points": 0 },
    "Marill": { "points": 0 },
    "Azumarill": { "points": 1 },
    "Sudowoodo": { "points": 0 },
    "Politoed": { "points": 0 },
    "Hoppip": { "points": 0 },
    "Skiploom": { "points": 0 },
    "Jumpluff": { "points": 0 },
    "Aipom": { "points": 0 },
    "Sunkern": { "points": 0 },
    "Sunflora": { "points": 0 },
    "Yanma": { "points": 0 },
    "Wooper": { "points": 0 },
    "Quagsire": { "points": 1 },
    "Espeon": { "points": 1 },
    "Umbreon": { "points": 1 },
    "Murkrow": { "points": 0 },
    "Slowking": { "points": 1 },
    "Misdreavous": { "points": 0 },
    "Unown": { "points": 0 },
    "Wobbuffet": { "points": 1 },
    "Girafarig": { "points": 0 },
    "Pineco": { "points": 0 },
    "Forretress": { "points": 1 },
    "Dunsparce": { "points": 0 },
    "Gligar": { "points": 1 },
    "Steelix": { "points": 0 },
    "Snubbull": { "points": 0 },
    "Granbull": { "points": 0 },
    "Qwilfish": { "points": 0 },
    "Scizor": { "points": 1 },
    "Shuckle": { "points": 1 },
    "Heracross": { "points": 1 },
    "Sneasel": { "points": 0 },
    "Teddiursa": { "points": 0 },
    "Ursaring": { "points": 0 },
    "Slugma": { "points": 0 },
    "Magcargo": { "points": 0 },
    "Swinub": { "points": 0 },
    "Piloswine": { "points": 0 },
    "Corsola": { "points": 0 },
    "Remoraid": { "points": 0 },
    "Octillery": { "points": 0 },
    "Delibird": { "points": 0 },
    "Mantine": { "points": 1 },
    "Skarmory": { "points": 1 },
    "Houndour": { "points": 0 },
    "Houndoom": { "points": 0 },
    "Kingdra": { "points": 0 },
    "Phanpy": { "points": 0 },
    "Donphan": { "points": 1 },
    "Porygon2": { "points": 1 },
    "Stantler": { "points": 0 },
    "Smeargle": { "points": 2 },
    "Tyrogue": { "points": 0 },
    "Hitmontop": { "points": 0 },
    "Smoochum": { "points": 0 },
    "Elekid": { "points": 0 },
    "Magby": { "points": 0 },
    "Miltank": { "points": 0 },
    "Blissey": { "points": 2 },
    "Raikou": { "points": 1 },
    "Entei": { "points": 1 },
    "Suicune": { "points": 1 },
    "Larvitar": { "points": 0 },
    "Pupitar": { "points": 0 },
    "Tyranitar": { "points": 1 },
    "Lugia": { "points": 2, "pointsHa": 3 },
    "Ho-Oh": { "points": 2, "pointsHa": 4 },
    "Celebi": { "points": 1 },
    "Treecko": { "points": 0 },
    "Grovyle": { "points": 0 },
    "Sceptile": { "points": 1, "pointsHa": 1 },
    "Torchic": { "points": 0 },
    "Combusken": { "points": 0 },
    "Blaziken": { "points": 0, "pointsHa": 2 },
    "Mudkip": { "points": 0 },
    "Marshtomp": { "points": 0 },
    "Swampert": { "points": 1 },
    "Poochyena": { "points": 0 },
    "Mightyena": { "points": 0 },
    "Zigzagoon": { "points": 0 },
    "Linoone": { "points": 1 },
    "Wurmple": { "points": 0 },
    "Silcoon": { "points": 0 },
    "Beautifly": { "points": 0 },
    "Cascoon": { "points": 0 },
    "Dustox": { "points": 0 },
    "Lotad": { "points": 0 },
    "Lombre": { "points": 0 },
    "Ludicolo": { "points": 0 },
    "Seedot": { "points": 0 },
    "Nuzleaf": { "points": 0 },
    "Shiftry": { "points": 0 },
    "Taillow": { "points": 0 },
    "Swellow": { "points": 0 },
    "Wingull": { "points": 0 },
    "Pelipper": { "points": 1 },
    "Ralts": { "points": 0 },
    "Kirlia": { "points": 0 },
    "Gardevoir": { "points": 1 },
    "Surskit": { "points": 0 },
    "Masquerain": { "points": 0 },
    "Shroomish": { "points": 0 },
    "Breloom": { "points": 1 },
    "Slakoth": { "points": 0 },
    "Vigoroth": { "points": 0 },
    "Slaking": { "points": 1 },
    "Nincada": { "points": 0 },
    "Ninjask": { "points": 2 },
    "Shedinja": { "points": 2 },
    "Whismur": { "points": 0 },
    "Loudred": { "points": 0 },
    "Exploud": { "points": 0 },
    "Makuhita": { "points": 0 },
    "Hariyama": { "points": 0 },
    "Azurill": { "points": 0 },
    "Nosepass": { "points": 0 },
    "Skitty": { "points": 0 },
    "Delcatty": { "points": 0 },
    "Sableye": { "points": 1 },
    "Mawile": { "points": 0 },
    "Aron": { "points": 1 },
    "Lairon": { "points": 1 },
    "Aggron": { "points": 1 },
    "Meditite": { "points": 0 },
    "Medicham": { "points": 0 },
    "Electrike": { "points": 0 },
    "Manectric": { "points": 0 },
    "Plusle": { "points": 0 },
    "Minun": { "points": 0 },
    "Volbeat": { "points": 0 },
    "Illumise": { "points": 0 },
    "Roselia": { "points": 0 },
    "Gulpin": { "points": 0 },
    "Swalot": { "points": 0 },
    "Carvanha": { "points": 0 },
    "Sharpedo": { "points": 0, "pointsHa": 2 },
    "Wailmer": { "points": 0 },
    "Wailord": { "points": 0 },
    "Numel": { "points": 0 },
    "Camerupt": { "points": 0 },
    "Torkoal": { "points": 0 },
    "Spoink": { "points": 0 },
    "Grumpig": { "points": 0 },
    "Spinda": { "points": 0 },
    "Trapinch": { "points": 0 },
    "Vibrava": { "points": 0 },
    "Flygon": { "points": 1 },
    "Cacnea": { "points": 0 },
    "Cacturne": { "points": 0 },
    "Swablu": { "points": 0 },
    "Altaria": { "points": 0 },
    "Zangoose": { "points": 0, "pointsHa": 1 },
    "Seviper": { "points": 0 },
    "Lunatone": { "points": 0 },
    "Solrock": { "points": 0 },
    "Barboach": { "points": 0 },
    "Whiscash": { "points": 0 },
    "Corphish": { "points": 0 },
    "Crawdaunt": { "points": 2 },
    "Baltoy": { "points": 0 },
    "Claydol": { "points": 0 },
    "Lileep": { "points": 0 },
    "Cradily": { "points": 0 },
    "Anorith": { "points": 0 },
    "Armaldo": { "points": 0 },
    "Feebas": { "points": 0 },
    "Milotic": { "points": 0 },
    "Castform": { "points": 0 },
    "Kecleon": { "points": 0 },
    "Shuppet": { "points": 0 },
    "Banette": { "points": 0 },
    "Duskull": { "points": 0 },
    "Dusclops": { "points": 1 },
    "Tropius": { "points": 0, "pointsHa": 1 },
    "Chimecho": { "points": 0 },
    "Absol": { "points": 0 },
    "Wynaut": { "points": 0 },
    "Snorunt": { "points": 0 },
    "Glalie": { "points": 1, "pointsHa": 2 },
    "Spheal": { "points": 0 },
    "Sealeo": { "points": 0 },
    "Walrein": { "points": 0 },
    "Clamperl": { "points": 0 },
    "Huntail": { "points": 0 },
    "Gorebyss": { "points": 0 },
    "Relicanth": { "points": 0 },
    "Luvdisc": { "points": 0 },
    "Bagon": { "points": 0 },
    "Shelgon": { "points": 0 },
    "Salamence": { "points": 1 },
    "Beldum": { "points": 0 },
    "Metang": { "points": 0 },
    "Metagross": { "points": 1 },
    "Regirock": { "points": 1 },
    "Regice": { "points": 1 },
    "Registeel": { "points": 1 },
    "Latias": { "points": 2 },
    "Latios": { "points": 2 },
    "Kyogre": { "points": 4 },
    "Groudon": { "points": 4 },
    "Rayquaza": { "points": 5 },
    "Jirachi": { "points": 2 },
    "Deoxys": { "points": 3 },
    "Turtwig": { "points": 0 },
    "Grotle": { "points": 0 },
    "Torterra": { "points": 0 },
    "Chimchar": { "points": 0 },
    "Monferno": { "points": 0 },
    "Infernape": { "points": 0 },
    "Piplup": { "points": 0 },
    "Prinplup": { "points": 0 },
    "Empoleon": { "points": 0 },
    "Starly": { "points": 0 },
    "Staravia": { "points": 0 },
    "Staraptor": { "points": 0 },
    "Bidoof": { "points": 0 },
    "Bibarel": { "points": 0 },
    "Kricketot": { "points": 0 },
    "Kricketune": { "points": 0 },
    "Shinx": { "points": 0 },
    "Luxio": { "points": 0 },
    "Luxray": { "points": 0 },
    "Budew": { "points": 0 },
    "Roserade": { "points": 1 },
    "Cranidos": { "points": 0 },
    "Rampardos": { "points": 1 },
    "Shieldon": { "points": 0 },
    "Bastiodon": { "points": 0 },
    "Burmy": { "points": 0 },
    "Wormadam": { "points": 0 },
    "Mothim": { "points": 0 },
    "Combee": { "points": 0 },
    "Vespiquen": { "points": 0 },
    "Pachirisu": { "points": 0 },
    "Buizel": { "points": 0 },
    "Floatzel": { "points": 0 },
    "Cherubi": { "points": 0 },
    "Cherrim": { "points": 0 },
    "Shellos": { "points": 0 },
    "Gastrodon": { "points": 1 },
    "Ambipom": { "points": 0 },
    "Drifloon": { "points": 0 },
    "Drifblim": { "points": 0 },
    "Buneary": { "points": 0 },
    "Lopunny": { "points": 0 },
    "Mismagius": { "points": 0 },
    "Honchkrow": { "points": 1 },
    "Glameow": { "points": 0 },
    "Purugly": { "points": 0 },
    "Chingling": { "points": 0 },
    "Stunky": { "points": 0 },
    "Skuntank": { "points": 0 },
    "Bronzor": { "points": 0 },
    "Bronzong": { "points": 0 },
    "Bonsly": { "points": 0 },
    "Mime Jr.": { "points": 0 },
    "Happiny": { "points": 0 },
    "Chatot": { "points": 0 },
    "Spiritomb": { "points": 0 },
    "Gible": { "points": 0 },
    "Gabite": { "points": 0 },
    "Garchomp": { "points": 1 },
    "Munchlax": { "points": 0 },
    "Riolu": { "points": 0 },
    "Lucario": { "points": 1 },
    "Hippopotas": { "points": 0 },
    "Hippowdon": { "points": 1 },
    "Skorupi": { "points": 0 },
    "Drapion": { "points": 0 },
    "Croagunk": { "points": 0 },
    "Toxicroak": { "points": 0 },
    "Carnivine": { "points": 0 },
    "Finneon": { "points": 0 },
    "Lumineon": { "points": 0 },
    "Mantyke": { "points": 0 },
    "Snover": { "points": 0 },
    "Abomasnow": { "points": 0 },
    "Weavile": { "points": 2 },
    "Magnezone": { "points": 1 },
    "Lickilicky": { "points": 0 },
    "Rhyperior": { "points": 1 },
    "Tangrowth": { "points": 1 },
    "Electivire": { "points": 1 },
    "Magmortar": { "points": 0 },
    "Togekiss": { "points": 2 },
    "Yanmega": { "points": 1 },
    "Leafeon": { "points": 1 },
    "Glaceon": { "points": 1 },
    "Gliscor": { "points": 1, "pointsHa": 2 },
    "Mamoswine": { "points": 1 },
    "Porygon-Z": { "points": 1 },
    "Gallade": { "points": 0 },
    "Probopass": { "points": 0 },
    "Dusknoir": { "points": 1 },
    "Froslass": { "points": 0 },
    "Rotom": { "points": 1 },
    "Uxie": { "points": 1 },
    "Mesprit": { "points": 1 },
    "Azelf": { "points": 1 },
    "Dialga": { "points": 3 },
    "Palkia": { "points": 3 },
    "Heatran": { "points": 3 },
    "Regigigas": { "points": 1 },
    "Giratina": { "points": 3 },
    "Cresselia": { "points": 1 },
    "Phione": { "points": 0 },
    "Manaphy": { "points": 1 },
    "Darkrai": { "points": 4 },
    "Shaymin": { "points": 1 },
    "Arceus": { "points": 4 },
    "Victini": { "points": 2 },
    "Snivy": { "points": 0 },
    "Servine": { "points": 0 },
    "Serperior": { "points": 0, "pointsHa": 2 },
    "Tepig": { "points": 0 },
    "Pignite": { "points": 0 },
    "Emboar": { "points": 0 },
    "Oshawott": { "points": 0 },
    "Dewott": { "points": 0 },
    "Samurott": { "points": 0 },
    "Patrat": { "points": 0 },
    "Watchog": { "points": 0 },
    "Lillipup": { "points": 0 },
    "Herdier": { "points": 0 },
    "Stoutland": { "points": 0 },
    "Purrloin": { "points": 0 },
    "Liepard": { "points": 0 },
    "Pansage": { "points": 0 },
    "Simisage": { "points": 0 },
    "Pansear": { "points": 0 },
    "Simisear": { "points": 0 },
    "Panpour": { "points": 0 },
    "Simipour": { "points": 0 },
    "Munna": { "points": 0 },
    "Musharna": { "points": 0 },
    "Pidove": { "points": 0 },
    "Tranquill": { "points": 0 },
    "Unfezant": { "points": 0 },
    "Blitzle": { "points": 0 },
    "Zebstrika": { "points": 0 },
    "Roggenrola": { "points": 0 },
    "Boldore": { "points": 0 },
    "Gigalith": { "points": 1 },
    "Woobat": { "points": 0 },
    "Swoobat": { "points": 0, "pointsHa": 1 },
    "Drilbur": { "points": 0 },
    "Excadrill": { "points": 1 },
    "Audino": { "points": 0 },
    "Timburr": { "points": 0 },
    "Gurdurr": { "points": 0 },
    "Conkeldurr": { "points": 1 },
    "Tympole": { "points": 0 },
    "Palpitoad": { "points": 0 },
    "Seismitoad": { "points": 1 },
    "Throh": { "points": 0 },
    "Sawk": { "points": 0 },
    "Sewaddle": { "points": 0 },
    "Swadloon": { "points": 0 },
    "Leavanny": { "points": 0 },
    "Venipede": { "points": 0 },
    "Whirlipede": { "points": 0 },
    "Scolipede": { "points": 1 },
    "Cottonee": { "points": 1 },
    "Whimsicott": { "points": 1 },
    "Petilil": { "points": 0 },
    "Lilligant": { "points": 0 },
    "Basculin": { "points": 0 },
    "Sandile": { "points": 0 },
    "Krokorok": { "points": 0 },
    "Krookodile": { "points": 1 },
    "Darumaka": { "points": 0 },
    "Darmanitan": { "points": 1 },
    "Maractus": { "points": 0 },
    "Dwebble": { "points": 0 },
    "Crustle": { "points": 0 },
    "Scraggy": { "points": 0 },
    "Scrafty": { "points": 0 },
    "Sigilyph": { "points": 0 },
    "Yamask": { "points": 0 },
    "Cofagrigus": { "points": 1 },
    "Tirtouga": { "points": 0 },
    "Carracosta": { "points": 1 },
    "Archen": { "points": 0 },
    "Archeops": { "points": 0 },
    "Trubbish": { "points": 0 },
    "Garbodor": { "points": 0 },
    "Zorua": { "points": 0 },
    "Zoroark": { "points": 1 },
    "Minccino": { "points": 0 },
    "Cinccino": { "points": 0 },
    "Gothita": { "points": 0 },
    "Gothorita": { "points": 0 },
    "Gothitelle": { "points": 2 },
    "Solosis": { "points": 0 },
    "Duosion": { "points": 0 },
    "Reuniclus": { "points": 2 },
    "Ducklett": { "points": 0 },
    "Swanna": { "points": 0 },
    "Vanillite": { "points": 0 },
    "Vanillish": { "points": 0 },
    "Vanilluxe": { "points": 0 },
    "Deerling": { "points": 0 },
    "Sawsbuck": { "points": 0 },
    "Emolga": { "points": 0 },
    "Karrablast": { "points": 0 },
    "Escavalier": { "points": 0 },
    "Foongus": { "points": 0 },
    "Amoonguss": { "points": 1, "pointsHa": 1 },
    "Frillish": { "points": 0 },
    "Jellicent": { "points": 0 },
    "Alomomola": { "points": 1 },
    "Joltik": { "points": 0 },
    "Galvantula": { "points": 1 },
    "Ferroseed": { "points": 0 },
    "Ferrothorn": { "points": 3 },
    "Klink": { "points": 0 },
    "Klang": { "points": 0 },
    "Klinklang": { "points": 0 },
    "Tynamo": { "points": 0 },
    "Eelektrik": { "points": 0 },
    "Eelektross": { "points": 0 },
    "Elgyem": { "points": 0 },
    "Beheeyem": { "points": 0 },
    "Litwick": { "points": 0 },
    "Lampent": { "points": 0 },
    "Chandelure": { "points": 1 },
    "Axew": { "points": 0 },
    "Fraxure": { "points": 0 },
    "Haxorus": { "points": 1 },
    "Cubchoo": { "points": 0 },
    "Beartic": { "points": 0 },
    "Cryogonal": { "points": 0 },
    "Shelmet": { "points": 0 },
    "Accelgor": { "points": 1 },
    "Stunfisk": { "points": 0 },
    "Mienfoo": { "points": 0 },
    "Mienshao": { "points": 1 },
    "Druddigon": { "points": 0 },
    "Golett": { "points": 0 },
    "Golurk": { "points": 0 },
    "Pawniard": { "points": 0 },
    "Bisharp": { "points": 1 },
    "Bouffalant": { "points": 0 },
    "Rufflet": { "points": 0 },
    "Braviary": { "points": 0 },
    "Vullaby": { "points": 0 },
    "Mandibuzz": { "points": 1 },
    "Heatmor": { "points": 0 },
    "Durant": { "points": 1 },
    "Deino": { "points": 0 },
    "Zweilous": { "points": 0 },
    "Hydreigon": { "points": 1 },
    "Larvesta": { "points": 0 },
    "Volcarona": { "points": 1 },
    "Cobalion": { "points": 1 },
    "Terrakion": { "points": 1 },
    "Virizion": { "points": 1 },
    "Tornadus": { "points": 1 },
    "Thundurus": { "points": 1 },
    "Reshiram": { "points": 2 },
    "Zekrom": { "points": 3 },
    "Landorus": { "points": 1, "pointsHa": 2 },
    "Kyurem": { "points": 2 },
    "Keldeo": { "points": 1 },
    "Meloetta": { "points": 1 },
    "Genesect": { "points": 2 },
    "Chespin": { "points": 0 },
    "Quilladin": { "points": 0 },
    "Chesnaught": { "points": 0 },
    "Fennekin": { "points": 0 },
    "Braixen": { "points": 0 },
    "Delphox": { "points": 0 },
    "Froakie": { "points": 0 },
    "Frogadier": { "points": 0 },
    "Greninja": { "points": 1, "pointsHa": 2 },
    "Bunnelby": { "points": 0 },
    "Diggersby": { "points": 1 },
    "Fletchling": { "points": 0 },
    "Fletchinder": { "points": 0 },
    "Talonflame": { "points": 1 },
    "Scatterbug": { "points": 0 },
    "Spewpa": { "points": 0 },
    "Vivillon": { "points": 0 },
    "Litleo": { "points": 0 },
    "Pyroar": { "points": 0 },
    "Flabébé": { "points": 0 },
    "Floette": { "points": 0 },
    "Florges": { "points": 1 },
    "Skiddo": { "points": 0 },
    "Gogoat": { "points": 0 },
    "Pancham": { "points": 0 },
    "Pangoro": { "points": 0 },
    "Furfrou": { "points": 0 },
    "Espurr": { "points": 0 },
    "Meowstic": { "points": 0 },
    "Honedge": { "points": 0 },
    "Doublade": { "points": 1 },
    "Aegislash": { "points": 2 },
    "Spritzee": { "points": 0 },
    "Aromatisse": { "points": 0 },
    "Swirlix": { "points": 0 },
    "Slurpuff": { "points": 1 },
    "Inkay": { "points": 0 },
    "Malamar": { "points": 1 },
    "Binacle": { "points": 0 },
    "Barbaracle": { "points": 1 },
    "Skrelp": { "points": 0 },
    "Dragalge": { "points": 0 },
    "Clauncher": { "points": 0 },
    "Clawitzer": { "points": 0 },
    "Helioptile": { "points": 0 },
    "Heliolisk": { "points": 0 },
    "Tyrunt": { "points": 0 },
    "Tyrantrum": { "points": 0 },
    "Amaura": { "points": 0 },
    "Aurorus": { "points": 0 },
    "Sylveon": { "points": 1 },
    "Hawlucha": { "points": 1 },
    "Dedenne": { "points": 0 },
    "Carbink": { "points": 0 },
    "Goomy": { "points": 0 },
    "Sliggoo": { "points": 0 },
    "Goodra": { "points": 1 },
    "Klefki": { "points": 1 },
    "Phantump": { "points": 0 },
    "Trevenant": { "points": 0 },
    "Pumpkaboo": { "points": 0 },
    "Gourgeist": { "points": 0 },
    "Bergmite": { "points": 0 },
    "Avalugg": { "points": 0 },
    "Noibat": { "points": 0 },
    "Noivern": { "points": 0 },
    "Xerneas": { "points": 5 },
    "Yveltal": { "points": 5 },
    "Zygarde": { "points": 2 },
    "Diancie": { "points": 1 },
    "Hoopa": { "points": 0 },
    "Volcanion": { "points": 2 },
    "Rowlet": { "points": 0 },
    "Dartrix": { "points": 0 },
    "Decidueye": { "points": 0 },
    "Litten": { "points": 0 },
    "Torracat": { "points": 0 },
    "Incineroar": { "points": 1 },
    "Popplio": { "points": 0 },
    "Brionne": { "points": 0 },
    "Primarina": { "points": 1 },
    "Pikipek": { "points": 0 },
    "Trumbeak": { "points": 0 },
    "Toucannon": { "points": 0 },
    "Yungoos": { "points": 0 },
    "Gumshoos": { "points": 0 },
    "Grubbin": { "points": 0 },
    "Charjabug": { "points": 0 },
    "Vikavolt": { "points": 1 },
    "Crabrawler": { "points": 0 },
    "Crabominable": { "points": 0 },
    "Oricorio": { "points": 0 },
    "Cutiefly": { "points": 0 },
    "Ribombee": { "points": 1 },
    "Rockruff": { "points": 0 },
    "Lycanroc": { "points": 1 },
    "Wishiwashi": { "points": 0 },
    "Mareanie": { "points": 0 },
    "Toxapex": { "points": 3 },
    "Mudbray": { "points": 0 },
    "Mudsdale": { "points": 0 },
    "Dewpider": { "points": 0 },
    "Araquanid": { "points": 1 },
    "Fomantis": { "points": 0 },
    "Lurantis": { "points": 1 },
    "Morelull": { "points": 0 },
    "Shiinotic": { "points": 0 },
    "Salandit": { "points": 0 },
    "Salazzle": { "points": 1 },
    "Stufful": { "points": 0 },
    "Bewear": { "points": 0 },
    "Bounsweet": { "points": 0 },
    "Steenee": { "points": 0 },
    "Tsareena": { "points": 0 },
    "Comfey": { "points": 1 },
    "Oranguru": { "points": 0 },
    "Passimian": { "points": 0 },
    "Wimpod": { "points": 0 },
    "Golisopod": { "points": 1 },
    "Sandygast": { "points": 0 },
    "Palossand": { "points": 0 },
    "Pyukumuku": { "points": 1 },
    "Type:Null": { "points": 0 },
    "Silvally": { "points": 1 },
    "Minior": { "points": 1 },
    "Komala": { "points": 1 },
    "Turtonator": { "points": 0 },
    "Togedemaru": { "points": 0, "pointsHa": 1 },
    "Mimikyu": { "points": 1 },
    "Bruxish": { "points": 0 },
    "Drampa": { "points": 0 },
    "Dhelmise": { "points": 0 },
    "Jangmo-o": { "points": 0 },
    "Hakamo-o": { "points": 0 },
    "Kommo-o": { "points": 1 },
    "Tapu Koko": { "points": 2 },
    "Tapu Lele": { "points": 2 },
    "Tapu Bulu": { "points": 1 },
    "Tapu Fini": { "points": 2 },
    "Cosmog": { "points": 0 },
    "Cosmoem": { "points": 0 },
    "Solgaleo": { "points": 3 },
    "Lunala": { "points": 3 },
    "Nihilego": { "points": 2 },
    "Buzzwole": { "points": 2 },
    "Pheromosa": { "points": 3 },
    "Xurkitree": { "points": 2 },
    "Celesteela": { "points": 2 },
    "Kartana": { "points": 2 },
    "Guzzlord": { "points": 1 },
    "Necrozma": { "points": 1 },
    "Magearna": { "points": 2 },
    "Marshadow": { "points": 4 },
    "Poipole": { "points": 0 },
    "Naganadel": { "points": 2 },
    "Stakataka": { "points": 1 },
    "Blacephalon": { "points": 2 },
    "Zeraora": { "points": 2 },
    "Meltan": { "points": 0 },
    "Melmetal": { "points": 3 },
    "Grookey": { "points": 0 },
    "Thwackey": { "points": 0 },
    "Rillaboom": { "points": 2 },
    "Scorbunny": { "points": 0 },
    "Raboot": { "points": 0 },
    "Cinderace": { "points": 1, "pointsHa": 2 },
    "Sobble": { "points": 0 },
    "Drizzile": { "points": 0 },
    "Inteleon": { "points": 1 },
    "Skwovet": { "points": 0 },
    "Greedent": { "points": 0 },
    "Rookidee": { "points": 0 },
    "Corvisquire": { "points": 0 },
    "Corviknight": { "points": 1 },
    "Blipbug": { "points": 0 },
    "Dottler": { "points": 0 },
    "Orbeetle": { "points": 0 },
    "Nickit": { "points": 0 },
    "Thievul": { "points": 0 },
    "Gossifleur": { "points": 0 },
    "Eldegoss": { "points": 0 },
    "Wooloo": { "points": 0 },
    "Dubwool": { "points": 1 },
    "Chewtle": { "points": 0 },
    "Drednaw": { "points": 1 },
    "Yamper": { "points": 0 },
    "Boltund": { "points": 0 },
    "Rolycoly": { "points": 0 },
    "Carkol": { "points": 0 },
    "Coalossal": { "points": 0 },
    "Applin": { "points": 0 },
    "Flapple": { "points": 0 },
    "Appletun": { "points": 1 },
    "Silicobra": { "points": 0 },
    "Sandaconda": { "points": 1 },
    "Cramorant": { "points": 0 },
    "Arrokuda": { "points": 0 },
    "Barraskewda": { "points": 2 },
    "Toxel": { "points": 0 },
    "Toxtricity": { "points": 0 },
    "Sizzlipede": { "points": 0 },
    "Centiskorch": { "points": 1 },
    "Clobbopus": { "points": 0 },
    "Grapploct": { "points": 0 },
    "Sinistea": { "points": 0 },
    "Polteageist": { "points": 1 },
    "Hatenna": { "points": 0 },
    "Hattrem": { "points": 0 },
    "Hatterene": { "points": 1 },
    "Impidimp": { "points": 0 },
    "Morgrem": { "points": 0 },
    "Grimmsnarl": { "points": 1 },
    "Obstagoon": { "points": 1 },
    "Perrserker": { "points": 0 },
    "Cursola": { "points": 1 },
    "Sirfetch'd": { "points": 0 },
    "Mr.Rime": { "points": 0 },
    "Runerigus": { "points": 0 },
    "Milcery": { "points": 0 },
    "Alcremie": { "points": 0 },
    "Falinks": { "points": 1 },
    "Pincurchin": { "points": 0 },
    "Snom": { "points": 0 },
    "Frosmoth": { "points": 0 },
    "Stonjourner": { "points": 0 },
    "Eiscue": { "points": 1 },
    "Indeedee": { "points": 1, "pointsHa": 1 },
    "Morpeko": { "points": 0 },
    "Cufant": { "points": 0 },
    "Copperajah": { "points": 0 },
    "Dracozolt": { "points": 1 },
    "Arctozolt": { "points": 1 },
    "Dracovish": { "points": 3 },
    "Arctovish": { "points": 0 },
    "Duraludon": { "points": 0 },
    "Dreepy": { "points": 0 },
    "Drakloak": { "points": 0 },
    "Dragapult": { "points": 2 },
    "Zacian": { "points": 5 },
    "Zamazenta": { "points": 3 },
    "Eternatus": { "points": 4 },
    "Kubfu": { "points": 0 },
    "Urshifu": { "points": 3 },
    "Zarude": { "points": 1 },
    "Regieleki": { "points": 3 },
    "Regidrago": { "points": 1 },
    "Glastrier": { "points": 2 },
    "Spectrier": { "points": 3 },
    "Calyrex": { "points": 0 },
    "Wyrdeer": { "points": 0 },
    "Kleavor": { "points": 1 },
    "Ursaluna": { "points": 2 },
    "Basculegion": { "points": 0 },
    "Sneasler": { "points": 1 },
    "Overqwil": { "points": 0 },
    "Enamorus": { "points": 2 },
    "Sprigatito": { "points": -1 },
    "Floragato": { "points": -1 },
    "Meowscarada": { "points": -1 },
    "Fuecoco": { "points": -1 },
    "Crocalor": { "points": -1 },
    "Skeledirge": { "points": -1 },
    "Quaxly": { "points": -1 },
    "Quaxwell": { "points": -1 },
    "Quaquaval": { "points": -1 },
    "Lechonk": { "points": -1 },
    "Oinkologne": { "points": -1 },
    "Tarountula": { "points": -1 },
    "Spidops": { "points": -1 },
    "Nymble": { "points": -1 },
    "Lokix": { "points": -1 },
    "Pawmi": { "points": -1 },
    "Pawmo": { "points": -1 },
    "Pawmot": { "points": -1 },
    "Tandemaus": { "points": -1 },
    "Maushold": { "points": -1 },
    "Fidough": { "points": -1 },
    "Dachsbun": { "points": -1 },
    "Smoliv": { "points": -1 },
    "Dolliv": { "points": -1 },
    "Arboliva": { "points": -1 },
    "Squawkabilly": { "points": -1 },
    "Nacli": { "points": -1 },
    "Naclstack": { "points": -1 },
    "Garganacl": { "points": -1 },
    "Charcadet": { "points": -1 },
    "Armarouge": { "points": -1 },
    "Ceruledge": { "points": -1 },
    "Tadbulb": { "points": -1 },
    "Bellibolt": { "points": -1 },
    "Wattrel": { "points": -1 },
    "Kilowattrel": { "points": -1 },
    "Maschiff": { "points": -1 },
    "Mabosstiff": { "points": -1 },
    "Shroodle": { "points": -1 },
    "Grafaiai": { "points": -1 },
    "Bramblin": { "points": -1 },
    "Brambleghast": { "points": -1 },
    "Toedscool": { "points": -1 },
    "Toedscruel": { "points": -1 },
    "Klawf": { "points": -1 },
    "Capsakid": { "points": -1 },
    "Scovillain": { "points": -1 },
    "Rellor": { "points": -1 },
    "Rabsca": { "points": -1 },
    "Flittle": { "points": -1 },
    "Espathra": { "points": -1 },
    "Tinkatink": { "points": -1 },
    "Tinkatuff": { "points": -1 },
    "Tinkaton": { "points": -1 },
    "Wiglett": { "points": -1 },
    "Wugtrio": { "points": -1 },
    "Bombirdier": { "points": -1 },
    "Finizen": { "points": -1 },
    "Palafin": { "points": -1 },
    "Varoom": { "points": -1 },
    "Revavroom": { "points": -1 },
    "Cyclizar": { "points": -1 },
    "Orthworm": { "points": -1 },
    "Glimmet": { "points": -1 },
    "Glimmora": { "points": -1 },
    "Greavard": { "points": -1 },
    "Houndstone": { "points": -1 },
    "Flamigo": { "points": -1 },
    "Cetoddle": { "points": -1 },
    "Cetitan": { "points": -1 },
    "Veluza": { "points": -1 },
    "Dondozo": { "points": -1 },
    "Tatsugiri": { "points": -1 },
    "Annihilipe": { "points": -1 },
    "Clodsire": { "points": -1 },
    "Farigiraf": { "points": -1 },
    "Dudunsparce": { "points": -1 },
    "Kingambit": { "points": -1 },
    "Great Task": { "points": -1 },
    "Scream Tail": { "points": -1 },
    "Brute Bonnet": { "points": -1 },
    "Flutter Mane": { "points": -1 },
    "Slither Wing": { "points": -1 },
    "Sandy Shocks": { "points": -1 },
    "Iron Treads": { "points": -1 },
    "Iron Bundle": { "points": -1 },
    "Iron Hands": { "points": -1 },
    "Iron Jugulis": { "points": -1 },
    "Iron Moth": { "points": -1 },
    "Iron Thorns": { "points": -1 },
    "Frigibax": { "points": -1 },
    "Arctibax": { "points": -1 },
    "Baxcalibur": { "points": -1 },
    "Gimmighoul": { "points": -1 },
    "Gholdengo": { "points": -1 },
    "Wo-Chien": { "points": -1 },
    "Chien-Pao": { "points": -1 },
    "Ting-Lu": { "points": -1 },
    "Chi-Yu": { "points": -1 },
    "Roaring Moon": { "points": -1 },
    "Iron Valiant": { "points": -1 },
    "Koraidon": { "points": -1 },
    "Miraidon": { "points": -1 },
    "Walking Wake": { "points": -1 },
    "Iron Leaves": { "points": -1 },
    "Dipplin": { "points": -1 },
    "Poltchageist": { "points": -1 },
    "Sinistcha": { "points": -1 },
    "Okidogi": { "points": -1 },
    "Munkidori": { "points": -1 },
    "Fezandipiti": { "points": -1 },
    "Ogerpon": { "points": -1 },
    "Archaludon": { "points": -1 },
    "Hydrapple": { "points": -1 },
    "Gouging Fire": { "points": -1 },
    "Raging Bolt": { "points": -1 },
    "Iron Boulder": { "points": -1 },
    "Iron Crown": { "points": -1 },
    "Terapagos": { "points": -1 },
    "Pecharunt": { "points": -1 },
}

formsPointsValue = {
    "Venusaur-Mega": {"points": 3},
    "Charizard-Mega-X": {"points": 1},
    "Charizard-Mega-Y": {"points": 1},
    "Blastoise-Mega": {"points": 3},
    "Beedrill-Mega": {"points": 2},
    "Pidgeot-Mega": {"points": 1},
    "Rattata-Alola": {"points": 0},
    "Raticate-Alola": {"points": 0},
    "Raichu-Alola": {"points": 1},
    "Sandshrew-Alola": {"points": 0},
    "Sandslash-Alola": {"points": 0},
    "Vulpix-Alola": {"points": 0},
    "Ninetales-Alola": {"points": 0, 'pointsHa': 1},
    "Diglett-Alola": {"points": 0},
    "Dugtrio-Alola": {"points": 0},
    "Meowth-Alola": {"points": 0},
    "Meowth-Galar": {"points": 0},
    "Persian-Alola": {"points": 0},
    "Growlithe-Hisui": {"points": 0},
    "Arcanine-Hisui": {"points": 0},
    "Alakazam-Mega": {"points": 2},
    "Geodude-Alola": {"points": 0},
    "Golem-Alola": {"points": 0},
    "Ponyta-Galar": {"points": 0},
    "Rapidash-Galar": {"points": 0},
    "Slowpoke-Galar": {"points": 0},
    "Slowbro-Mega": {"points": 2},
    "Slowbro-Galar": {"points": 1},
    "Farfetch'd-Galar": {"points": 0},
    "Grimer-Alola": {"points": 0},
    "Muk-Alola": {"points": 0},
    "Gengar-Mega": {"points": 4},
    "Voltorb-Hisui": {"points": 0},
    "Electrode-Hisui": {"points": 1},
    "Exeggutor-Alola": {"points": 0},
    "Marowak-Alola": {"points": 1},
    "Weezing-Galar": {"points": 0},
    "Kangaskhan-Mega": {"points": 3},
    "Mr.Mime-Galar": {"points": 0},
    "Pinsir-Mega": {"points": 1},
    "Gyarados-Mega": {"points": 2},
    "Aerodactyl-Mega": {"points": 2},
    "Articuno-Galar": {"points": 1},
    "Zapdos-Galar": {"points": 2},
    "Moltres-Galar": {"points": 2},
    "Mewtwo-Mega-X": {"points": 4},
    "Mewtwo-Mega-Y": {"points": 4},
    "Typhlosion-Hisui": {"points": 0},
    "Ampharos-Mega": {"points": 1},
    "Slowking-Galar": {"points": 0},
    "Steelix-Mega": {"points": 1},
    "Qwilfish-Hisui": {"points": 0},
    "Scizor-Mega": {"points": 2},
    "Heracross-Mega": {"points": 2},
    "Sneasel-Hisui": {"points": 0},
    "Corsola-Galar": {"points": 1},
    "Houndoom-Mega": {"points": 1},
    "Tyranitar-Mega": {"points": 2},
    "Sceptile-Mega": {"points": 1},
    "Blaziken-Mega": {"points": 2},
    "Swampert-Mega": {"points": 2},
    "Zigzagoon-Galar": {"points": 0},
    "Linoone-Galar": {"points": 0},
    "Gardevoir-Mega": {"points": 2},
    "Sableye-Mega": {"points": 2},
    "Mawile-Mega": {"points": 2},
    "Aggron-Mega": {"points": 1},
    "Medicham-Mega": {"points": 2},
    "Manectric-Mega": {"points": 1},
    "Sharpedo-Mega": {"points": 1},
    "Camerupt-Mega": {"points": 1},
    "Altaria-Mega": {"points": 2},
    "Banette-Mega": {"points": 1},
    "Absol-Mega": {"points": 1},
    "Glalie-Mega": {"points": 2},
    "Salamence-Mega": {"points": 3},
    "Metagross-Mega": {"points": 3},
    "Latias-Mega": {"points": 3},
    "Latios-Mega": {"points": 3},
    "Kyogre-Primal": {"points": 5},
    "Groudon-Primal": {"points": 6},
    "Rayquaza-Mega": {"points": 6},
    "Deoxys-Attack": {"points": 3},
    "Deoxys-Defense": {"points": 2},
    "Deoxys-Speed": {"points": 3},
    "Wormadam-Sandy": {"points": 0},
    "Wormadam-Trash": {"points": 0},
    "Lopunny-Mega": {"points": 2},
    "Garchomp-Mega": {"points": 1},
    "Lucario-Mega": {"points": 3},
    "Abomasnow-Mega": {"points": 1},
    "Gallade-Mega": {"points": 2},
    "Rotom-Heat": {"points": 1},
    "Rotom-Wash": {"points": 1},
    "Rotom-Frost": {"points": 1},
    "Rotom-Fan": {"points": 1},
    "Rotom-Mow": {"points": 1},
    "Dialga-Origin": {"points": 3},
    "Palkia-Origin": {"points": 3},
    "Giratina-Origin": {"points": 3},
    "Shaymin-Sky": {"points": 3},
    "Arceus-Bug": {"points": 4},
    "Arceus-Dark": {"points": 4},
    "Arceus-Dragon": {"points": 4},
    "Arceus-Electric": {"points": 4},
    "Arceus-Fairy": {"points": 4},
    "Arceus-Fighting": {"points": 4},
    "Arceus-Fire": {"points": 4},
    "Arceus-Flying": {"points": 4},
    "Arceus-Ghost": {"points": 4},
    "Arceus-Grass": {"points": 4},
    "Arceus-Ground": {"points": 4},
    "Arceus-Ice": {"points": 4},
    "Arceus-Poison": {"points": 4},
    "Arceus-Psychic": {"points": 4},
    "Arceus-Rock": {"points": 4},
    "Arceus-Steel": {"points": 4},
    "Arceus-Water": {"points": 4},
    "Samurott-Hisui": {"points": 0},
    "Audino-Mega": {"points": 1},
    "Lilligant-Hisui": {"points": 0},
    "Darumaka-Galar": {"points": 0},
    "Darmanitan-Galar": {"points": 3},
    "Yamask-Galar": {"points": 0},
    "Zorua-Hisui": {"points": 0},
    "Zoroark-Hisui": {"points": 1},
    "Stunfisk-Galar": {"points": 0},
    "Braviary-Hisui": {"points": 0},
    "Tornadus-Therian": {"points": 1},
    "Thundurus-Therian": {"points": 1},
    "Landorus-Therian": {"points": 2},
    "Kyurem-Black": {"points": 4},
    "Kyurem-White": {"points": 3},
    "Meloetta-Piroutte": {"points": 1},
    "Greninja-Ash": {"points": 2},
    "Floette-Eternal": {"points": 0},
    "Sliggoo-Hisui": {"points": 0},
    "Goodra-Hisui": {"points": 2},
    "Avalugg-Hisui": {"points": 0},
    "Zygarde-10%": {"points": 1},
    "Zygarde-Complete": {"points": 4},
    "Diancie-Mega": {"points": 3},
    "Hoopa-Unbound": {"points": 2},
    "Decidueye-Hisui": {"points": 0},
    "Oricorio-Pa'u": {"points": 0},
    "Oricorio-Pom-Pom": {"points": 0},
    "Oricorio-Sensu": {"points": 0},
    "Lycanroc-Dusk": {"points": 1},
    "Lycanroc-Midnight": {"points": 1},
    "Wishiwashi-School": {"points": 0},
    "Necrozma-Dawn-Wings": {"points": 4},
    "Necrozma-Dusk-Mane": {"points": 4},
    "Necrozma-Ultra": {"points": 4},
    "Zacian-Crowned": {"points": 6},
    "Zamazenta-Crowned": {"points": 4},
    "Eternatus-Eternamax": {"points": 7},
    "Urshifu-Rapid-Strike": {"points": 3},
    "Calyrex-Ice": {"points": 4},
    "Calyrex-Shadow": {"points": 6},
    "Enamorus-Therian": {"points": 2},
}

def fetch_data_from_db(db_path):
    try:
        # Подключаемся к базе данных
        connection = sqlite3.connect(db_path)
        cursor = connection.cursor()

        # Выполняем запрос к базе данных
        cursor.execute("SELECT * FROM pokemons")  # Замените "your_table_name" на имя вашей таблицы
        # Получаем все строки из результата запроса
        rows = cursor.fetchall()
        
        # Формируем список словарей, представляющих строки данных
        data = []
        for row in rows:
            row_dict = {}
            for i, column_name in enumerate(cursor.description):
                row_dict[column_name[0]] = row[i]
            data.append(row_dict)
        return data
    except sqlite3.Error as e:
        print("Ошибка при работе с базой данных:", e)
        return None


    finally:
        # Закрываем соединение с базой данных
        if connection:
            connection.close()

# Пример использования функции
db_path = "pokemon.db"  # Укажите путь к вашей базе данных SQLite3
data = fetch_data_from_db(db_path)

typesBase = "https://play.pokemonshowdown.com/sprites/types/"

iconUrl = "https://play.pokemonshowdown.com/sprites/pokemonicons-sheet.png?v16"

def iconLocation(number):
    return "-" + str(number % 12 * 40) + "px -" + str(number // 12 * 30) + "px"

li_elements = ""
for idx, poke in enumerate(data):
        if not poke['changesFrom'] and poke['num'] < 1026 and poke['num'] > 0:
            poketypes = json.loads(poke['types'])
            li_elements += f'''
                <li class="buttons">
                    <a href="{poke['name'].lower()}.html">
                    <button>
                        <div class="pokemon-icon">
                            <span style="display:inline-block; width:40px; height:30px; background: transparent url({iconUrl}) no-repeat scroll {iconLocation(poke["num"])};">
                            </span>
                        </div>
                        <p class="pokemon-name">{poke['name']}</p>
                        <div class="pokemon-types">
                            <img id="type-img" src="{typesBase + poketypes[0] + '.png'}">
                            {'<img id="type-img" src="' + typesBase + poketypes[1] + '.png">' if len(poketypes) > 1 else ''}
                        </div>
                        <p class="pokemon-tier">{poke['tier']}</p>
                    </button></a>
                </li>
            '''

def generate_pokemon_page(pokemon):
    print(pokemon['name'])
    types = json.loads(pokemon['types'])
    base_stats = json.loads(pokemon['baseStats'])
    abilities = json.loads(pokemon['abilities'])
    
    
    
    html = f'''
        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>{pokemon['name']}</title>
            <link rel="stylesheet" href="../styles.css">
            <link rel="stylesheet" href="pokedex.css">
            <link rel="icon" href="https://www.smogon.com/dex/media/sprites/xy/{pokemon["name"].lower()}.gif" type="image/gif">
            <script src="pokedex.js"></script>
        </head>
        <body>
            <header>
                <div class="All_header_menu">
                    <div class="Logo">
                        <img src="../img/pokeball.png">
                    </div>
                    <ul id="navbar">
                        <li><a href="../index.html">Главная</a></li>
                        <li>
                            <a>Покедекс</a>
                            <ul>
                                <li><a href="bulbasaur.html">Покемоны</a></li>
                                <li><a href="moves.html">Атаки</a></li>
                                <li><a href="abilities.html">Способности</a></li>
                                <li><a href="types.html">Типы</a></li>
                            </ul> 
                        </li>
                        <li><a href="../help.html">Поддержка</a></li>
                        <li><a href="../register.html">Войти/Регистрация</a></li>
                    </ul>
                </div>
            </header>
            <div class="main">
                <div class="left-menu">
                    <ul>
                    <div class="search">
                        <input type="search" oninput="searchUpdate()">
                    </div>
                        {li_elements}
                    </ul>
                </div>
                <div class="pokemon-info">
                    <h1 class="block-inline">{pokemon['name']}</h1>
                    <div class="pokemon-info-top">
                        <div class="pokemon-image-container">
                            <div id="pokemon-image" style="background-image: url(https://www.smogon.com/dex/media/sprites/xy/{pokemon["name"].lower()}.gif)" alt="{pokemon['name']}">
                            </div>
                        </div>
                        <div class="pokemon-evolutions">
                            <div>
                                <div class="pokemon-icon">
                                    <span style="display:inline-block; width:40px; height:30px; background: transparent url({iconUrl}) no-repeat scroll {iconLocation(pokemon["num"])};"></span>
                                </div>
                                <h4>{pokemon['name']}</h4>
                            </div>
                        </div>
                        <div class="pokemon-stats">
                            <div>
                                <p class="stat-name">HP:</p>
                                <p class="stat-value">{base_stats["hp"]}</p>
                                <div class="stat-bar">
                                    <div class="progress" style="width: {(base_stats["hp"] / 250) * 100}%" data-color="{ 'red' if base_stats["hp"] <= 50 else 'green' if base_stats["hp"] >= 250 else 'orange' }"></div>
                                </div>
                            </div>
                            <div>
                                <p class="stat-name">Attack:</p>
                                <p class="stat-value">{base_stats["atk"]}</p>
                                <div class="stat-bar">
                                    <div class="progress" style="width: {(base_stats["atk"] / 250) * 100}%" data-color="{ 'red' if base_stats["atk"] <= 50 else 'green' if base_stats["atk"] >= 250 else 'orange' }"></div>
                                </div>
                            </div>
                            <div>
                                <p class="stat-name">Defense:</p>
                                <p class="stat-value">{base_stats["def"]}</p>
                                <div class="stat-bar">
                                    <div class="progress" style="width: {(base_stats["def"] / 250) * 100}%" data-color="{ 'red' if base_stats["def"] <= 50 else 'green' if base_stats["def"] >= 250 else 'orange' }"></div>
                                </div>
                            </div>
                            <div>
                                <p class="stat-name">Sp. Atk:</p>
                                <p class="stat-value">{base_stats["spa"]}</p>
                                <div class="stat-bar">
                                    <div class="progress" style="width: {(base_stats["spa"] / 250) * 100}%" data-color="{ 'red' if base_stats["spa"] <= 50 else 'green' if base_stats["spa"] >= 250 else 'orange' }"></div>
                                </div>
                            </div>
                            <div>
                                <p class="stat-name">Sp. Def:</p>
                                <p class="stat-value">{base_stats["spd"]}</p>
                                <div class="stat-bar">
                                    <div class="progress" style="width: {(base_stats["spd"] / 250) * 100}%" data-color="{ 'red' if base_stats["spd"] <= 50 else 'green' if base_stats["spd"] >= 250 else 'orange' }"></div>
                                </div>
                            </div>
                            <div>
                                <p class="stat-name">Speed:</p>
                                <p class="stat-value">{base_stats["spe"]}</p>
                                <div class="stat-bar">
                                    <div class="progress" style="width: {(base_stats["spe"] / 250) * 100}%" data-color="{ 'red' if base_stats["spe"] <= 50 else 'green' if base_stats["spe"] >= 250 else 'orange' }"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="block">
                        <div class="pokemon-types">
                            <p>Type:   </p>
                            <img id="type-img" src="{typesBase + types[0] + '.png'}">
                            {'<img id="type-img" src="' + typesBase + types[1] + '.png">' if len(types) > 1 else ''}
                        </div>
                        <div>
                            <p>Points: {pokemon['points']}</p>
                        </div>
                        {f"""
                        <div>
                            <p>HA points: {pokemon['pointsHa']}</p>
                        </div>""" if abilities.get("H") else ''
                        }
                        <div>
                            <p>Tier: {pokemon['tier']}</p>
                        </div>
                        <div class="pokemon-abilities">
                            <p>Abilities: {", ".join([ability for ability in [abilities.get("0"), abilities.get("1"), abilities.get("H")] if ability])}</p>
                        </div>
                        <div>
                            <p></p>
                        </div>
                    </div>
                </div>
            </div>
        </body>
        </html>
    '''
    return html

for pokemon in data:
    if not pokemon['changesFrom'] and pokemon['num'] < 1026 and pokemon['num'] > 0:
        page_content = generate_pokemon_page(pokemon)
        with open(pokemon['name'].lower() + '.html', 'w', encoding='utf-8') as file:
            file.write(page_content)